multiLangKeyboard.addKeyboard('German', 'de', [
  [
    {default: "^",      shift: "\u00b0", alt_shift: null,     alt: null, special: null       },
    {default: "1",      shift: "!",      alt_shift: null,     alt: null, special: null       },
    {default: "2",      shift: '"',      alt_shift: "\u00b2", alt: null, special: null       },
    {default: "3",      shift: "\u00a7", alt_shift: "\u00b3", alt: null, special: null       },
    {default: "4",      shift: "$",      alt_shift: null,     alt: null, special: null       },
    {default: "5",      shift: "%",      alt_shift: null,     alt: null, special: null       },
    {default: "6",      shift: "&",      alt_shift: null,     alt: null, special: null       },
    {default: "7",      shift: "/",      alt_shift: "{",      alt: null, special: null       },
    {default: "8",      shift: "(",      alt_shift: "[",      alt: null, special: null       },
    {default: "9",      shift: ")",      alt_shift: "]",      alt: null, special: null       },
    {default: "0",      shift: "=",      alt_shift: "}",      alt: null, special: null       },
    {default: "\u00df", shift: null,     alt_shift: "?",      alt: "\\", special: null       },
    {default: "\u00b4", shift: null,     alt_shift: "`",      alt: null, special: null       },
    {default: null,     shift: null,     alt_shift: null,     alt: null, special: "backspace"}
  ],
  [
    {default: null,     shift: null,     alt_shift: null,     alt: null, special: "spacer"},
    {default: "q",      shift: "Q",      alt_shift: "@",      alt: null, special: null    },
    {default: "w",      shift: "W",      alt_shift: null,     alt: null, special: null    },
    {default: "e",      shift: "E",      alt_shift: "\u20ac", alt: null, special: null    },
    {default: "r",      shift: "R",      alt_shift: null,     alt: null, special: null    },
    {default: "t",      shift: "T",      alt_shift: null,     alt: null, special: null    },
    {default: "z",      shift: "Z",      alt_shift: null,     alt: null, special: null    },
    {default: "u",      shift: "U",      alt_shift: null,     alt: null, special: null    },
    {default: "i",      shift: "I",      alt_shift: null,     alt: null, special: null    },
    {default: "o",      shift: "O",      alt_shift: null,     alt: null, special: null    },
    {default: "p",      shift: "P",      alt_shift: null,     alt: null, special: null    },
    {default: "\u00fc", shift: "\u00dc", alt_shift: null,     alt: null, special: null    },
    {default: "+",      shift: "*",      alt_shift: "~",      alt: null, special: null    },
    {default: "#",      shift: "'",      alt_shift: null,     alt: null, special: null    },
    {default: null,     shift: null,     alt_shift: null,     alt: null, special: "spacer"}
  ],
  [
    {default: null,     shift: null,     alt_shift: null, alt: null, special: "spacer"},
    {default: "a",      shift: "A",      alt_shift: null, alt: null, special: null    },
    {default: "s",      shift: "S",      alt_shift: null, alt: null, special: null    },
    {default: "d",      shift: "D",      alt_shift: null, alt: null, special: null    },
    {default: "f",      shift: "F",      alt_shift: null, alt: null, special: null    },
    {default: "g",      shift: "G",      alt_shift: null, alt: null, special: null    },
    {default: "h",      shift: "H",      alt_shift: null, alt: null, special: null    },
    {default: "j",      shift: "J",      alt_shift: null, alt: null, special: null    },
    {default: "k",      shift: "K",      alt_shift: null, alt: null, special: null    },
    {default: "l",      shift: "L",      alt_shift: null, alt: null, special: null    },
    {default: "\u00f6", shift: "\u00d6", alt_shift: null, alt: null, special: null    },
    {default: "\u00e4", shift: "\u00c4", alt_shift: null, alt: null, special: null    },
    {default: null,     shift: null,     alt_shift: null, alt: null, special: "enter" }
  ],
  [
    {default: null, shift: null, alt_shift: null,     alt: null, special: "shift"},
    {default: "<",  shift: ">",  alt_shift: "\u00a6", alt: null, special: null   },
    {default: "y",  shift: "Y",  alt_shift: null,     alt: null, special: null   },
    {default: "x",  shift: "X",  alt_shift: null,     alt: null, special: null   },
    {default: "c",  shift: "C",  alt_shift: null,     alt: null, special: null   },
    {default: "v",  shift: "V",  alt_shift: null,     alt: null, special: null   },
    {default: "b",  shift: "B",  alt_shift: null,     alt: null, special: null   },
    {default: "n",  shift: "N",  alt_shift: null,     alt: null, special: null   },
    {default: "m",  shift: "M",  alt_shift: "\u00b5", alt: null, special: null   },
    {default: ",",  shift: ";",  alt_shift: null,     alt: null, special: null   },
    {default: ".",  shift: ":",  alt_shift: null,     alt: null, special: null   },
    {default: "-",  shift: "_",  alt_shift: null,     alt: null, special: null   },
    {default: null, shift: null, alt_shift: null,     alt: null, special: "shift"}
  ],
  [
    {default: null, shift: null, alt_shift: null, alt: null, special: "spacer"},
    {default: null, shift: null, alt_shift: null, alt: null, special: "alt"   },
    {default: null, shift: null, alt_shift: null, alt: null, special: "space" },
    {default: null, shift: null, alt_shift: null, alt: null, special: "alt"   },
    {default: null, shift: null, alt_shift: null, alt: null, special: "spacer"}
  ]
]);
