multiLangKeyboard.addKeyboard('Persian', 'fa', [
  [
    {default: "\u067e", shift: "\u0651 ", alt_shift: null,     alt: null,     special: null       },
    {default: "1",      shift: "!",       alt_shift: "\u00a1", alt: "\u00b9", special: null       },
    {default: "2",      shift: "@",       alt_shift: "\u00b2", alt: null,     special: null       },
    {default: "3",      shift: "#",       alt_shift: "\u00b3", alt: null,     special: null       },
    {default: "4",      shift: "$",       alt_shift: "\u00a4", alt: "\u00a3", special: null       },
    {default: "5",      shift: "%",       alt_shift: "\u20ac", alt: null,     special: null       },
    {default: "6",      shift: "^",       alt_shift: "\u00bc", alt: null,     special: null       },
    {default: "7",      shift: "&",       alt_shift: "\u00bd", alt: null,     special: null       },
    {default: "8",      shift: "*",       alt_shift: "\u00be", alt: null,     special: null       },
    {default: "9",      shift: "(",       alt_shift: "\u2018", alt: null,     special: null       },
    {default: "0",      shift: ")",       alt_shift: "\u2019", alt: null,     special: null       },
    {default: "-",      shift: "_",       alt_shift: "\u00a5", alt: null,     special: null       },
    {default: "=",      shift: "+",       alt_shift: "\u00d7", alt: "\u00f7", special: null       },
    {default: null,     shift: null,      alt_shift: null,     alt: null,     special: "backspace"}
  ],
  [
    {default: null,     shift: null,     alt_shift: null, alt: null, special: "spacer"},
    {default: "\u0636", shift: "\u064e", alt_shift: null, alt: null, special: null    },
    {default: "\u0635", shift: "\u064b", alt_shift: null, alt: null, special: null    },
    {default: "\u062b", shift: "\u064f", alt_shift: null, alt: null, special: null    },
    {default: "\u0642", shift: "\u064c", alt_shift: null, alt: null, special: null    },
    {default: "\u0641", shift: "\u0644", alt_shift: null, alt: null, special: null    },
    {default: "\u063a", shift: "\u0625", alt_shift: null, alt: null, special: null    },
    {default: "\u0639", shift: "\u2018", alt_shift: null, alt: null, special: null    },
    {default: "\u0647", shift: "\u00f7", alt_shift: null, alt: null, special: null    },
    {default: "\u062e", shift: "\u00d7", alt_shift: null, alt: null, special: null    },
    {default: "\u062d", shift: "\u061b", alt_shift: null, alt: null, special: null    },
    {default: "\u062c", shift: "<",      alt_shift: null, alt: null, special: null    },
    {default: "\u0686", shift: ">",      alt_shift: null, alt: null, special: null    },
    {default: "\u0698", shift: "|",      alt_shift: null, alt: null, special: null    },
    {default: null,     shift: null,     alt_shift: null, alt: null, special: "spacer"},
  ],
  [
    {default: null,     shift: null,     alt_shift: null, alt: null, special: "spacer"},
    {default: "\u0634", shift: "\u0650", alt_shift: null, alt: null, special: null    },
    {default: "\u0633", shift: "\u064d", alt_shift: null, alt: null, special: null    },
    {default: "\u064a", shift: "]",      alt_shift: null, alt: null, special: null    },
    {default: "\u0628", shift: "[",      alt_shift: null, alt: null, special: null    },
    {default: "\u0644", shift: "\u0644", alt_shift: null, alt: null, special: null    },
    {default: "\u0627", shift: "\u0623", alt_shift: null, alt: null, special: null    },
    {default: "\u062a", shift: "\u0640", alt_shift: null, alt: null, special: null    },
    {default: "\u0646", shift: "\u060c", alt_shift: null, alt: null, special: null    },
    {default: "\u0645", shift: "\\",     alt_shift: null, alt: null, special: null    },
    {default: "\u06af", shift: ":",      alt_shift: null, alt: null, special: null    },
    {default: "\u0643", shift: '"',      alt_shift: null, alt: null, special: null    },
    {default: null,     shift: null,     alt_shift: null, alt: null, special: "enter" }
  ],
  [
    {default: null,     shift: null,     alt_shift: null, alt: null, special: "shift"},
    {default: "\u0638", shift: "~",      alt_shift: null, alt: null, special: null   },
    {default: "\u0637", shift: "\u0652", alt_shift: null, alt: null, special: null   },
    {default: "\u0632", shift: "}",      alt_shift: null, alt: null, special: null   },
    {default: "\u0631", shift: "{",      alt_shift: null, alt: null, special: null   },
    {default: "\u0630", shift: "\u0644", alt_shift: null, alt: null, special: null   },
    {default: "\u062f", shift: "\u0622", alt_shift: null, alt: null, special: null   },
    {default: "\u0626", shift: "\u0621", alt_shift: null, alt: null, special: null   },
    {default: "\u0648", shift: ",",      alt_shift: null, alt: null, special: null   },
    {default: ".",      shift: ".",      alt_shift: null, alt: null, special: null   },
    {default: "/",      shift: "\u061f", alt_shift: null, alt: null, special: null   },
    {default: null,     shift: null,     alt_shift: null, alt: null, special: "shift"}
  ],
  [
    {default: null, shift: null, alt_shift: null, alt: null, special: "spacer"},
    {default: null, shift: null, alt_shift: null, alt: null, special: "alt"   },
    {default: null, shift: null, alt_shift: null, alt: null, special: "space" },
    {default: null, shift: null, alt_shift: null, alt: null, special: "alt"   },
    {default: null, shift: null, alt_shift: null, alt: null, special: "spacer"}
  ]
]);
