multiLangKeyboard.addKeyboard('Belarusian', 'be', [
  [
    {default: "\u0451", shift: "\u0401", alt_shift: null, alt: null, special: null       },
    {default: "1",      shift: "!",      alt_shift: null, alt: null, special: null       },
    {default: "2",      shift: '"',      alt_shift: null, alt: null, special: null       },
    {default: "3",      shift: "\u2116", alt_shift: null, alt: null, special: null       },
    {default: "4",      shift: ";",      alt_shift: null, alt: null, special: null       },
    {default: "5",      shift: "%",      alt_shift: null, alt: null, special: null       },
    {default: "6",      shift: ":",      alt_shift: null, alt: null, special: null       },
    {default: "7",      shift: "?",      alt_shift: null, alt: null, special: null       },
    {default: "8",      shift: "*",      alt_shift: null, alt: null, special: null       },
    {default: "9",      shift: "(",      alt_shift: null, alt: null, special: null       },
    {default: "0",      shift: ")",      alt_shift: null, alt: null, special: null       },
    {default: "-",      shift: "_",      alt_shift: null, alt: null, special: null       },
    {default: "=",      shift: "+",      alt_shift: null, alt: null, special: null       },
    {default: null,     shift: null,     alt_shift: null, alt: null, special: "backspace"}
  ],
  [
    {default: null,     shift: null,     alt_shift: null, alt: null, special: "spacer"},
    {default: "\u0439", shift: "\u0419", alt_shift: null, alt: null, special: null    },
    {default: "\u0446", shift: "\u0426", alt_shift: null, alt: null, special: null    },
    {default: "\u0443", shift: "\u0423", alt_shift: null, alt: null, special: null    },
    {default: "\u043a", shift: "\u041a", alt_shift: null, alt: null, special: null    },
    {default: "\u0435", shift: "\u0415", alt_shift: null, alt: null, special: null    },
    {default: "\u043d", shift: "\u041d", alt_shift: null, alt: null, special: null    },
    {default: "\u0433", shift: "\u0413", alt_shift: null, alt: null, special: null    },
    {default: "\u0448", shift: "\u0428", alt_shift: null, alt: null, special: null    },
    {default: "\u045e", shift: "\u040e", alt_shift: null, alt: null, special: null    },
    {default: "\u0437", shift: "\u0417", alt_shift: null, alt: null, special: null    },
    {default: "\u0445", shift: "\u0425", alt_shift: null, alt: null, special: null    },
    {default: "'",      shift: "'",      alt_shift: null, alt: null, special: null    },
    {default: "\\",     shift: "/",      alt_shift: null, alt: null, special: null    },
    {default: null,     shift: null,     alt_shift: null, alt: null, special: "spacer"}
  ],
  [
    {default: null,     shift: null,     alt_shift: null, alt: null, special: "spacer"},
    {default: null,     shift: null,     alt_shift: null, alt: null, special: "spacer"},
    {default: null,     shift: null,     alt_shift: null, alt: null, special: "spacer"},
    {default: null,     shift: null,     alt_shift: null, alt: null, special: "spacer"},
    {default: null,     shift: null,     alt_shift: null, alt: null, special: "spacer"},
    {default: null,     shift: null,     alt_shift: null, alt: null, special: "spacer"},
    {default: null,     shift: null,     alt_shift: null, alt: null, special: "spacer"},
    {default: "\u0444", shift: "\u0424", alt_shift: null, alt: null, special: null   },
    {default: "\u044b", shift: "\u042b", alt_shift: null, alt: null, special: null   },
    {default: "\u0432", shift: "\u0412", alt_shift: null, alt: null, special: null   },
    {default: "\u0430", shift: "\u0410", alt_shift: null, alt: null, special: null   },
    {default: "\u043f", shift: "\u041f", alt_shift: null, alt: null, special: null   },
    {default: "\u0440", shift: "\u0420", alt_shift: null, alt: null, special: null   },
    {default: "\u043e", shift: "\u041e", alt_shift: null, alt: null, special: null   },
    {default: "\u043b", shift: "\u041b", alt_shift: null, alt: null, special: null   },
    {default: "\u0434", shift: "\u0414", alt_shift: null, alt: null, special: null   },
    {default: "\u0436", shift: "\u0416", alt_shift: null, alt: null, special: null   },
    {default: "\u044d", shift: "\u042d", alt_shift: null, alt: null, special: null   },
    {default: null,     shift: null,     alt_shift: null, alt: null, special: "enter" }
  ],
  [
    {default: null,     shift: null,     alt_shift: null, alt: null, special: "shift"},
    {default: "/",      shift: "|",      alt_shift: null, alt: null, special: null   },
    {default: "\u044f", shift: "\u042f", alt_shift: null, alt: null, special: null   },
    {default: "\u0447", shift: "\u0427", alt_shift: null, alt: null, special: null   },
    {default: "\u0441", shift: "\u0421", alt_shift: null, alt: null, special: null   },
    {default: "\u043c", shift: "\u041c", alt_shift: null, alt: null, special: null   },
    {default: "\u0456", shift: "\u0406", alt_shift: null, alt: null, special: null   },
    {default: "\u0442", shift: "\u0422", alt_shift: null, alt: null, special: null   },
    {default: "\u044c", shift: "\u042c", alt_shift: null, alt: null, special: null   },
    {default: "\u0431", shift: "\u0411", alt_shift: null, alt: null, special: null   },
    {default: "\u044e", shift: "\u042e", alt_shift: null, alt: null, special: null   },
    {default: ".",      shift: ",",      alt_shift: null, alt: null, special: null   },
    {default: null,     shift: null,     alt_shift: null, alt: null, special: "shift"}
  ],
  [
    {default: null, shift: null, alt_shift: null, alt: null, special: "spacer"},
    {default: null, shift: null, alt_shift: null, alt: null, special: "space" },
    {default: null, shift: null, alt_shift: null, alt: null, special: "spacer"}
  ]
]);
