multiLangKeyboard.addKeyboard('IPA - International Phonetic Alphabet', 'ipa', [
  [
    {default: "\u0251",        shift: null, alt_shift: null, alt: null, special: null,     title: 'open back unrounded vowel'          },
    {default: "\u00E6",        shift: null, alt_shift: null, alt: null, special: null,     title: 'near-open front unrounded vowel'    },
    {default: "\u0250",        shift: null, alt_shift: null, alt: null, special: null,     title: 'near-open central vowel'            },
    {default: "\u0251\u0303",  shift: null, alt_shift: null, alt: null, special: null,     title: 'nasalized open back unrounded vowel'},
    {default: null,            shift: null, alt_shift: null, alt: null, special: 'spacer', title: ''                                   },
    {default: "\u03B2",        shift: null, alt_shift: null, alt: null, special: null,     title: 'voiced bilabial fricative'          },
    {default: "\u0253",        shift: null, alt_shift: null, alt: null, special: null,     title: 'voiced bilabial implosive'          },
    {default: "\u0299",        shift: null, alt_shift: null, alt: null, special: null,     title: 'bilabial trill'                     },
    {default: null,            shift: null, alt_shift: null, alt: null, special: 'spacer', title: ''                                   },
    {default: "\u0255",        shift: null, alt_shift: null, alt: null, special: null,     title: 'voiceless alveo-palatal fricative'  },
    {default: "\u00E7",        shift: null, alt_shift: null, alt: null, special: null,     title: 'voiceless palatal fricative'        },
    {default: null,            shift: null, alt_shift: null, alt: null, special: 'spacer', title: ''                                   },
    {default: "\u00F0",        shift: null, alt_shift: null, alt: null, special: null,     title: 'voiced dental fricative'            },
    {default: "d\u0361\u0292", shift: null, alt_shift: null, alt: null, special: null,     title: 'voiced postalveolar affricate'      },
    {default: "\u0256",        shift: null, alt_shift: null, alt: null, special: null,     title: 'voiced retroflex plosive'           },
    {default: '\u0257',        shift: null, alt_shift: null, alt: null, special: null,     title: 'voiced alveolar implosive'          },
    {default: null,            shift: null, alt_shift: null, alt: null, special: 'spacer', title: ''                                   },
    {default: '\u0259',        shift: null, alt_shift: null, alt: null, special: null,     title: 'mid-central vowel'                  },
    {default: '\u025A',        shift: null, alt_shift: null, alt: null, special: null,     title: 'rhotacized mid-central vowel'       },
    {default: '\u0275',        shift: null, alt_shift: null, alt: null, special: null,     title: 'close-mid central rounded vowel'    },
    {default: '\u0258',        shift: null, alt_shift: null, alt: null, special: null,     title: 'close-mid central unrounded vowel'  }
  ],
  [
    {default: '\u025B',       shift: null, alt_shift: null, alt: null, special: null,     title: 'open-mid front unrounded vowel'             },
    {default: '\u025C',       shift: null, alt_shift: null, alt: null, special: null,     title: 'open-mid central unrounded vowel'           },
    {default: '\u025D',       shift: null, alt_shift: null, alt: null, special: null,     title: 'rhotacized open-mid central unrounded vowel'},
    {default: '\u025B\u0303', shift: null, alt_shift: null, alt: null, special: null,     title: 'nasalized open-mid front unrounded vowel'   },
    {default: '\u025E',       shift: null, alt_shift: null, alt: null, special: null,     title: 'open-mid central rounded vowel'             },
    {default: null,           shift: null, alt_shift: null, alt: null, special: 'spacer', title: ''                                           },
    {default: '\u0260',       shift: null, alt_shift: null, alt: null, special: null,     title: 'voiced velar implosive'                     },
    {default: '\u0262',       shift: null, alt_shift: null, alt: null, special: null,     title: 'voiced uvular plosive'                      },
    {default: '\u029B',       shift: null, alt_shift: null, alt: null, special: null,     title: 'voiced uvular implosive'                    },
    {default: null,           shift: null, alt_shift: null, alt: null, special: 'spacer', title: ''                                           },
    {default: '\u0265',       shift: null, alt_shift: null, alt: null, special: null,     title: 'labial-palatal approximant'                 },
    {default: '\u0266',       shift: null, alt_shift: null, alt: null, special: null,     title: 'voiced glottal fricative'                   },
    {default: '\u0127',       shift: null, alt_shift: null, alt: null, special: null,     title: 'voiceless pharyngeal fricative'             },
    {default: '\u0267',       shift: null, alt_shift: null, alt: null, special: null,     title: 'Sje-sound'                                  },
    {default: '\u029C',       shift: null, alt_shift: null, alt: null, special: null,     title: 'voiceless epiglottal fricative'             },
    {default: null,           shift: null, alt_shift: null, alt: null, special: 'spacer', title: ''                                           },
    {default: '\u026A',       shift: null, alt_shift: null, alt: null, special: null,     title: 'near-close near-front unrounded vowel'      },
    {default: '\u026A\u0308', shift: null, alt_shift: null, alt: null, special: null,     title: 'near-close central unrounded vowel'         },
    {default: '\u0268',       shift: null, alt_shift: null, alt: null, special: null,     title: 'close central unrounded vowel'              },
    {default: null,           shift: null, alt_shift: null, alt: null, special: 'spacer', title: ''                                           },
    {default: '\u029D',       shift: null, alt_shift: null, alt: null, special: null,     title: 'voiced palatal fricative'                   },
    {default: '\u025F',       shift: null, alt_shift: null, alt: null, special: null,     title: 'voiced palatal plosive'                     },
    {default: '\u0284',       shift: null, alt_shift: null, alt: null, special: null,     title: 'voiced palatal implosive'                   }
  ],
  [
    {default: '\u026B',       shift: null, alt_shift: null, alt: null, special: null,     title: 'velarized alveolar lateral approximant'},
    {default: '\u026C',       shift: null, alt_shift: null, alt: null, special: null,     title: 'voiceless alveolar lateral fricative'  },
    {default: '\u029F',       shift: null, alt_shift: null, alt: null, special: null,     title: 'velar lateral approximant'             },
    {default: '\u026D',       shift: null, alt_shift: null, alt: null, special: null,     title: 'retroflex lateral approximant'         },
    {default: '\u026E',       shift: null, alt_shift: null, alt: null, special: null,     title: 'voiced alveolar lateral fricative'     },
    {default: null,           shift: null, alt_shift: null, alt: null, special: 'spacer', title: ''                                      },
    {default: '\u0271',       shift: null, alt_shift: null, alt: null, special: null,     title: 'labiodental nasal'                     },
    {default: null,           shift: null, alt_shift: null, alt: null, special: 'spacer', title: ''                                      },
    {default: '\u014B',       shift: null, alt_shift: null, alt: null, special: null,     title: 'velar nasal'                           },
    {default: '\u0272',       shift: null, alt_shift: null, alt: null, special: null,     title: 'palatal nasal'                         },
    {default: '\u0274',       shift: null, alt_shift: null, alt: null, special: null,     title: 'uvular nasal'                          },
    {default: '\u0273',       shift: null, alt_shift: null, alt: null, special: null,     title: 'retroflex nasal'                       },
    {default: null,           shift: null, alt_shift: null, alt: null, special: 'spacer', title: ''                                      },
    {default: '\u0254',       shift: null, alt_shift: null, alt: null, special: null,     title: 'open-mid back rounded vowel'           },
    {default: '\u0153',       shift: null, alt_shift: null, alt: null, special: null,     title: 'open-mid front rounded vowel'          },
    {default: '\u00F8',       shift: null, alt_shift: null, alt: null, special: null,     title: 'close-mid front rounded vowel'         },
    {default: '\u0252',       shift: null, alt_shift: null, alt: null, special: null,     title: 'open back rounded vowel'               },
    {default: '\u0254\u0303', shift: null, alt_shift: null, alt: null, special: null,     title: 'nasalized open-mid back rounded vowel' },
    {default: '\u0276',       shift: null, alt_shift: null, alt: null, special: null,     title: 'open front rounded vowel'              },
    {default: null,           shift: null, alt_shift: null, alt: null, special: 'spacer', title: ''                                      },
    {default: '\u0278',       shift: null, alt_shift: null, alt: null, special: null,     title: 'voiceless bilabial fricative'          }
  ],
  [
    {default: '\u027E',        shift: null, alt_shift: null, alt: null, special: null,     title: 'alveolar tap'                      },
    {default: '\u0281',        shift: null, alt_shift: null, alt: null, special: null,     title: 'voiced uvular fricative'           },
    {default: '\u0279',        shift: null, alt_shift: null, alt: null, special: null,     title: 'alveolar approximant'              },
    {default: '\u027B',        shift: null, alt_shift: null, alt: null, special: null,     title: 'retroflex approximant'             },
    {default: '\u0280',        shift: null, alt_shift: null, alt: null, special: null,     title: 'uvular trill'                      },
    {default: '\u027D',        shift: null, alt_shift: null, alt: null, special: null,     title: 'retroflex flap'                    },
    {default: '\u027A',        shift: null, alt_shift: null, alt: null, special: null,     title: 'alveolar lateral flap'             },
    {default: null,            shift: null, alt_shift: null, alt: null, special: 'spacer', title: ''                                  },
    {default: '\u0283',        shift: null, alt_shift: null, alt: null, special: null,     title: 'voiceless postalveolar fricative'  },
    {default: '\u0282',        shift: null, alt_shift: null, alt: null, special: null,     title: 'voiceless retroflex fricative'     },
    {default: null,            shift: null, alt_shift: null, alt: null, special: 'spacer', title: ''                                  },
    {default: '\u03B8',        shift: null, alt_shift: null, alt: null, special: null,     title: 'voiceless dental fricative'        },
    {default: 't\u0361\u0283', shift: null, alt_shift: null, alt: null, special: null,     title: 'voiceless postalveolar affricate'  },
    {default: 't\u0361s',      shift: null, alt_shift: null, alt: null, special: null,     title: 'voiceless alveolar affricate'      },
    {default: '\u0288',        shift: null, alt_shift: null, alt: null, special: null,     title: 'voiceless retroflex plosive'       },
    {default: null,            shift: null, alt_shift: null, alt: null, special: 'spacer', title: ''                                  },
    {default: '\u028A',        shift: null, alt_shift: null, alt: null, special: null,     title: 'near-close near-back rounded vowel'},
    {default: '\u028A\u0308',  shift: null, alt_shift: null, alt: null, special: null,     title: 'near-close central rounded vowel'  },
    {default: '\u0289',        shift: null, alt_shift: null, alt: null, special: null,     title: 'close central rounded vowel'       },
    {default: null,            shift: null, alt_shift: null, alt: null, special: 'spacer', title: ''                                  },
    {default: '\u028C',        shift: null, alt_shift: null, alt: null, special: null,     title: 'open-mid back unrounded vowel'     },
    {default: '\u028B',        shift: null, alt_shift: null, alt: null, special: null,     title: 'labiodental approximant'           },
    {default: '\u2C71',        shift: null, alt_shift: null, alt: null, special: null,     title: 'labiodental flap'                  } /* not available in Lucida, Cambria, Calibri; available in Arial 7, Times 7 */
  ],
  [
    {default: '\u028D', shift: null, alt_shift: null, alt: null, special: null,     title: 'voiceless labio-velar approximant'  },
    {default: '\u026F', shift: null, alt_shift: null, alt: null, special: null,     title: 'close back unrounded vowel'         },
    {default: '\u0270', shift: null, alt_shift: null, alt: null, special: null,     title: 'velar approximant'                  },
    {default: null,     shift: null, alt_shift: null, alt: null, special: 'spacer', title: ''                                   },
    {default: '\u03C7', shift: null, alt_shift: null, alt: null, special: null,     title: 'voiceless uvular fricative'         },
    {default: null,     shift: null, alt_shift: null, alt: null, special: 'spacer', title: ''                                   },
    {default: '\u028E', shift: null, alt_shift: null, alt: null, special: null,     title: 'palatal lateral approximant'        },
    {default: '\u0263', shift: null, alt_shift: null, alt: null, special: null,     title: 'voiced velar fricative'             },
    {default: '\u028F', shift: null, alt_shift: null, alt: null, special: null,     title: 'near-close near-front rounded vowel'},
    {default: '\u0264', shift: null, alt_shift: null, alt: null, special: null,     title: 'close-mid back unrounded vowel'     },
    {default: null,     shift: null, alt_shift: null, alt: null, special: 'spacer', title: ''                                   },
    {default: '\u0292', shift: null, alt_shift: null, alt: null, special: null,     title: 'voiced postalveolar fricative'      },
    {default: '\u0290', shift: null, alt_shift: null, alt: null, special: null,     title: 'voiced retroflex fricative'         },
    {default: '\u0291', shift: null, alt_shift: null, alt: null, special: null,     title: 'voiced alveolo-palatal fricative'   },
    {default: null,     shift: null, alt_shift: null, alt: null, special: 'spacer', title: ''                                   },
    {default: '\u0294', shift: null, alt_shift: null, alt: null, special: null,     title: 'glottal stop'                       },
    {default: '\u0295', shift: null, alt_shift: null, alt: null, special: null,     title: 'voiced pharyngeal fricative'        },
    {default: '\u02A2', shift: null, alt_shift: null, alt: null, special: null,     title: 'voiced epiglottal fricative'        },
    {default: '\u02A1', shift: null, alt_shift: null, alt: null, special: null,     title: 'epiglottal plosive'                 },
    {default: null,     shift: null, alt_shift: null, alt: null, special: 'spacer', title: ''                                   },
    {default: '\u007C', shift: null, alt_shift: null, alt: null, special: null,     title: 'minor group'                        },
    {default: '\u2016', shift: null, alt_shift: null, alt: null, special: null,     title: 'major group'                        }, /* problems in IE 5, 6 */
    {default: '\u2205', shift: null, alt_shift: null, alt: null, special: null,     title: 'zero'                               }
  ],
  [
    {default: '\u02C8', shift: null, alt_shift: null, alt: null, special: null,     title: 'primary stress'   },
    {default: '\u02CC', shift: null, alt_shift: null, alt: null, special: null,     title: 'secondary stress' },
    {default: null,     shift: null, alt_shift: null, alt: null, special: 'spacer', title: ''                 },
    {default: '\u02D0', shift: null, alt_shift: null, alt: null, special: null,     title: 'length mark'      },
    {default: '\u02D1', shift: null, alt_shift: null, alt: null, special: null,     title: 'half-long'        },
    {default: '\u0306', shift: null, alt_shift: null, alt: null, special: null,     title: 'extra short'      },
    {default: null,     shift: null, alt_shift: null, alt: null, special: 'spacer', title: ''                 },
    {default: '\u0361', shift: null, alt_shift: null, alt: null, special: null,     title: 'tie bar'          },
    {default: '\u035C', shift: null, alt_shift: null, alt: null, special: null,     title: 'tie bar'          },
    {default: '\u203F', shift: null, alt_shift: null, alt: null, special: null,     title: 'linking'          }, /* problems in IE 5, 6, 7 */
    {default: null,     shift: null, alt_shift: null, alt: null, special: 'spacer', title: ''                 },
    {default: '\u2192', shift: null, alt_shift: null, alt: null, special: null,     title: 'becomes (Alt+→→→)'},
    {default: '\u0308', shift: null, alt_shift: null, alt: null, special: null,     title: 'centralized'      },
    {default: '\u0303', shift: null, alt_shift: null, alt: null, special: null,     title: 'nasalized'        },
    {default: '\u0325', shift: null, alt_shift: null, alt: null, special: null,     title: 'voiceless'        },
    {default: '\u030A', shift: null, alt_shift: null, alt: null, special: null,     title: 'voiceless'        },
    {default: '\u032C', shift: null, alt_shift: null, alt: null, special: null,     title: 'voiced'           },
    {default: '\u0329', shift: null, alt_shift: null, alt: null, special: null,     title: 'syllabic'         },
    {default: '\u032F', shift: null, alt_shift: null, alt: null, special: null,     title: 'non-syllabic'     }
  ],
  [
    {default: '\u1D4A', shift: null, alt_shift: null, alt: null, special: null, title: 'syllabic or schwa'   },
    {default: '\u02B3', shift: null, alt_shift: null, alt: null, special: null, title: 'optional r'          },
    {default: '\u02DE', shift: null, alt_shift: null, alt: null, special: null, title: 'rhotacized'          },
    {default: '\u02B0', shift: null, alt_shift: null, alt: null, special: null, title: 'aspirated'           },
    {default: '\u02B7', shift: null, alt_shift: null, alt: null, special: null, title: 'labialized'          },
    {default: '\u02B2', shift: null, alt_shift: null, alt: null, special: null, title: 'palatalized'         },
    {default: '\u031D', shift: null, alt_shift: null, alt: null, special: null, title: 'raised'              },
    {default: '\u031F', shift: null, alt_shift: null, alt: null, special: null, title: 'advanced (fronted)'  },
    {default: '\u0320', shift: null, alt_shift: null, alt: null, special: null, title: 'retracted (backed)'  },
    {default: '\u031A', shift: null, alt_shift: null, alt: null, special: null, title: 'not audibly released'}
  ],
  [
    {default: '\u030F', shift: null, alt_shift: null, alt: null, special: null,     title: 'extra low'                  },
    {default: '\u0300', shift: null, alt_shift: null, alt: null, special: null,     title: 'low'                        },
    {default: '\u0304', shift: null, alt_shift: null, alt: null, special: null,     title: 'mid'                        },
    {default: '\u0301', shift: null, alt_shift: null, alt: null, special: null,     title: 'high'                       },
    {default: '\u030B', shift: null, alt_shift: null, alt: null, special: null,     title: 'extra high'                 },
    {default: '\u0302', shift: null, alt_shift: null, alt: null, special: null,     title: 'falling'                    },
    {default: '\u030C', shift: null, alt_shift: null, alt: null, special: null,     title: 'rising'                     },
    {default: '\u1DC5', shift: null, alt_shift: null, alt: null, special: null,     title: 'low rising'                 },
    {default: '\u1DC4', shift: null, alt_shift: null, alt: null, special: null,     title: 'high rising'                },
    {default: '\u1DC8', shift: null, alt_shift: null, alt: null, special: null,     title: 'rising-falling'             },
    {default: null,     shift: null, alt_shift: null, alt: null, special: 'spacer', title: ''                           },
    {default: '\u01C0', shift: null, alt_shift: null, alt: null, special: null,     title: 'dental click'               },
    {default: '\u01C1', shift: null, alt_shift: null, alt: null, special: null,     title: 'lateral click'              },
    {default: '\u01C2', shift: null, alt_shift: null, alt: null, special: null,     title: 'palatal click'              },
    {default: '\u01C3', shift: null, alt_shift: null, alt: null, special: null,     title: '(post-)alveolar click'      },
    {default: '\u0298', shift: null, alt_shift: null, alt: null, special: null,     title: 'bilabial click'             },
    {default: null,     shift: null, alt_shift: null, alt: null, special: 'spacer', title: ''                           },
    {default: '\u2019', shift: null, alt_shift: null, alt: null, special: null,     title: 'apostrophe'                 },
    {default: '\u201C', shift: null, alt_shift: null, alt: null, special: null,     title: 'English-style opening quote'},
    {default: '\u201D', shift: null, alt_shift: null, alt: null, special: null,     title: 'English-style closing quote'},
    {default: '\u2013', shift: null, alt_shift: null, alt: null, special: null,     title: 'endash'                     },
    {default: '\u2014', shift: null, alt_shift: null, alt: null, special: null,     title: 'emdash'                     }
  ],
  [
    {default: '\u0261', shift: null, alt_shift: null, alt: null, special: null, title: 'script g'                   },
    {default: '\u02BC', shift: null, alt_shift: null, alt: null, special: null, title: 'ejective'                   },
    {default: '\u032A', shift: null, alt_shift: null, alt: null, special: null, title: 'dental'                     },
    {default: '\u033A', shift: null, alt_shift: null, alt: null, special: null, title: 'apical'                     },
    {default: '\u0339', shift: null, alt_shift: null, alt: null, special: null, title: 'more rounded'               },
    {default: '\u031C', shift: null, alt_shift: null, alt: null, special: null, title: 'less rounded'               },
    {default: '\u033D', shift: null, alt_shift: null, alt: null, special: null, title: 'mid-centralized'            },
    {default: '\u0324', shift: null, alt_shift: null, alt: null, special: null, title: 'breathy voiced'             },
    {default: '\u0330', shift: null, alt_shift: null, alt: null, special: null, title: 'creaky voiced'              },
    {default: '\u033C', shift: null, alt_shift: null, alt: null, special: null, title: 'linguolabial'               },
    {default: '\u02E0', shift: null, alt_shift: null, alt: null, special: null, title: 'velarized'                  },
    {default: '\u02E4', shift: null, alt_shift: null, alt: null, special: null, title: 'pharyngealized'             },
    {default: '\u0318', shift: null, alt_shift: null, alt: null, special: null, title: 'stød'                       },
    {default: '\u0319', shift: null, alt_shift: null, alt: null, special: null, title: 'retracted tongue root'      },
    {default: '\u033B', shift: null, alt_shift: null, alt: null, special: null, title: 'laminal'                    },
    {default: '\u0301', shift: null, alt_shift: null, alt: null, special: null, title: 'combining acute accent'     },
    {default: '\u0300', shift: null, alt_shift: null, alt: null, special: null, title: 'combining grave accent'     }
  ],
  [
    {default: '\u02E9',             shift: null, alt_shift: null, alt: null, special: null, title: 'extra low'     },
    {default: '\u02E8',             shift: null, alt_shift: null, alt: null, special: null, title: 'low'           },
    {default: '\u02E7',             shift: null, alt_shift: null, alt: null, special: null, title: 'mid'           },
    {default: '\u02E6',             shift: null, alt_shift: null, alt: null, special: null, title: 'high'          },
    {default: '\u02E5',             shift: null, alt_shift: null, alt: null, special: null, title: 'extra high'    },
    {default: '\u02E5\u02E9',       shift: null, alt_shift: null, alt: null, special: null, title: 'falling'       },
    {default: '\u02E9\u02E5',       shift: null, alt_shift: null, alt: null, special: null, title: 'rising'        },
    {default: '\u02E9\u02E8',       shift: null, alt_shift: null, alt: null, special: null, title: 'low rising'    },
    {default: '\u02E6\u02E5',       shift: null, alt_shift: null, alt: null, special: null, title: 'high rising'   },
    {default: '\u02E7\u02E6\u02E7', shift: null, alt_shift: null, alt: null, special: null, title: 'rising-falling'},
    {default: '\u2193',             shift: null, alt_shift: null, alt: null, special: null, title: 'downstep'      },
    {default: '\u2191',             shift: null, alt_shift: null, alt: null, special: null, title: 'upstep'        },
    {default: '\u2198',             shift: null, alt_shift: null, alt: null, special: null, title: 'global fall'   },
    {default: '\u2197',             shift: null, alt_shift: null, alt: null, special: null, title: 'global rise'   }
  ],
  [
    {default: null, shift: null, alt_shift: null, alt: null, special: "spacer"},
    {default: null, shift: null, alt_shift: null, alt: null, special: "space" },
    {default: null, shift: null, alt_shift: null, alt: null, special: "spacer"}
  ]
]);
