multiLangKeyboard.addKeyboard('Hungarian', 'hu', [
  [
    {default: "0",      shift: "\u00a7", alt_shift: null,     alt: null, special: null       },
    {default: "1",      shift: "'",      alt_shift: "~",      alt: null, special: null       },
    {default: "2",      shift: '"',      alt_shift: "\u02c7", alt: null, special: null       },
    {default: "3",      shift: "+",      alt_shift: "\u02c6", alt: null, special: null       },
    {default: "4",      shift: "!",      alt_shift: "\u02d8", alt: null, special: null       },
    {default: "5",      shift: "%",      alt_shift: "\u00b0", alt: null, special: null       },
    {default: "6",      shift: "/",      alt_shift: "\u02db", alt: null, special: null       },
    {default: "7",      shift: "=",      alt_shift: "`",      alt: null, special: null       },
    {default: "8",      shift: "(",      alt_shift: "\u02d9", alt: null, special: null       },
    {default: "9",      shift: ")",      alt_shift: "\u00b4", alt: null, special: null       },
    {default: "\u00f6", shift: "\u00d6", alt_shift: "\u02dd", alt: null, special: null       },
    {default: "\u00fc", shift: "\u00dc", alt_shift: "\u00a8", alt: null, special: null       },
    {default: "\u00f3", shift: "\u00d3", alt_shift: "\u00b8", alt: null, special: null       },
    {default: null,     shift: null,     alt_shift: null,     alt: null, special: "backspace"}
  ],
  [
    {default: null,     shift: null,     alt_shift: null,     alt: null, special: "spacer"},
    {default: "q",      shift: "Q",      alt_shift: "\\",     alt: null, special: null    },
    {default: "w",      shift: "W",      alt_shift: "|",      alt: null, special: null    },
    {default: "e",      shift: "E",      alt_shift: "\u00c4", alt: null, special: null    },
    {default: "r",      shift: "R",      alt_shift: null,     alt: null, special: null    },
    {default: "t",      shift: "T",      alt_shift: null,     alt: null, special: null    },
    {default: "z",      shift: "Z",      alt_shift: null,     alt: null, special: null    },
    {default: "u",      shift: "U",      alt_shift: "\u20ac", alt: null, special: null    },
    {default: "i",      shift: "I",      alt_shift: "\u00cd", alt: null, special: null    },
    {default: "o",      shift: "O",      alt_shift: null,     alt: null, special: null    },
    {default: "p",      shift: "P",      alt_shift: null,     alt: null, special: null    },
    {default: "\u0151", shift: "\u0150", alt_shift: "\u00f7", alt: null, special: null    },
    {default: "\u00fa", shift: "\u00da", alt_shift: "\u00d7", alt: null, special: null    },
    {default: "\u0171", shift: "\u0170", alt_shift: "\u00a4", alt: null, special: null    },
    {default: null,     shift: null,     alt_shift: null,     alt: null, special: "spacer"}
  ],
  [
    {default: null,     shift: null,     alt_shift: null,     alt: null, special: "spacer"},
    {default: null,     shift: null,     alt_shift: null,     alt: null, special: "spacer"},
    {default: null,     shift: null,     alt_shift: null,     alt: null, special: "spacer"},
    {default: "a",      shift: "A",      alt_shift: "\u00e4", alt: null, special: null    },
    {default: "s",      shift: "S",      alt_shift: "\u0111", alt: null, special: null    },
    {default: "d",      shift: "D",      alt_shift: "\u0110", alt: null, special: null    },
    {default: "f",      shift: "F",      alt_shift: "[",      alt: null, special: null    },
    {default: "g",      shift: "G",      alt_shift: "]",      alt: null, special: null    },
    {default: "h",      shift: "H",      alt_shift: null,     alt: null, special: null    },
    {default: "j",      shift: "J",      alt_shift: "\u00ed", alt: null, special: null    },
    {default: "k",      shift: "K",      alt_shift: "\u0141", alt: null, special: null    },
    {default: "l",      shift: "L",      alt_shift: "\u0142", alt: null, special: null    },
    {default: "\u00e9", shift: "\u00c9", alt_shift: "$",      alt: null, special: null    },
    {default: "\u00e1", shift: "\u00c1", alt_shift: "\u00df", alt: null, special: null    },
    {default: null,     shift: null,     alt_shift: null,     alt: null, special: "enter" }
  ],
  [
    {default: null,     shift: null,     alt_shift: null, alt: null, special: "shift"},
    {default: "\u00ed", shift: "\u00cd", alt_shift: "<",  alt: null, special: null   },
    {default: "y",      shift: "Y",      alt_shift: ">",  alt: null, special: null   },
    {default: "x",      shift: "X",      alt_shift: "#",  alt: null, special: null   },
    {default: "c",      shift: "C",      alt_shift: "&",  alt: null, special: null   },
    {default: "v",      shift: "V",      alt_shift: "@",  alt: null, special: null   },
    {default: "b",      shift: "B",      alt_shift: "{",  alt: null, special: null   },
    {default: "n",      shift: "N",      alt_shift: "}",  alt: null, special: null   },
    {default: "m",      shift: "M",      alt_shift: "<",  alt: null, special: null   },
    {default: ",",      shift: "?",      alt_shift: ";",  alt: null, special: null   },
    {default: ".",      shift: ":",      alt_shift: ">",  alt: null, special: null   },
    {default: "-",      shift: "_",      alt_shift: "*",  alt: null, special: null   },
    {default: null,     shift: null,     alt_shift: null, alt: null, special: "shift"}
  ],
  [
    {default: null, shift: null, alt_shift: null, alt: null, special: "spacer"},
    {default: null, shift: null, alt_shift: null, alt: null, special: "alt"   },
    {default: null, shift: null, alt_shift: null, alt: null, special: "space" },
    {default: null, shift: null, alt_shift: null, alt: null, special: "alt"   },
    {default: null, shift: null, alt_shift: null, alt: null, special: "spacer"}
  ]
]);
