multiLangKeyboard.addKeyboard('Danish', 'da', [
  [
    {default: "\u00bd", shift: "\u00a7", alt_shift: null,     alt: null, special: null       },
    {default: "1",      shift: "!",      alt_shift: null,     alt: null, special: null       },
    {default: "2",      shift: '"',      alt_shift: "@",      alt: null, special: null       },
    {default: "3",      shift: "#",      alt_shift: "\u00a3", alt: null, special: null       },
    {default: "4",      shift: "\u00a4", alt_shift: "$",      alt: null, special: null       },
    {default: "5",      shift: "%",      alt_shift: "\u20ac", alt: null, special: null       },
    {default: "6",      shift: "&",      alt_shift: null,     alt: null, special: null       },
    {default: "7",      shift: "/",      alt_shift: "{",      alt: null, special: null       },
    {default: "8",      shift: "(",      alt_shift: "[",      alt: null, special: null       },
    {default: "9",      shift: ")",      alt_shift: "]",      alt: null, special: null       },
    {default: "0",      shift: "=",      alt_shift: "}",      alt: null, special: null       },
    {default: "+",      shift: "?",      alt_shift: null,     alt: null, special: null       },
    {default: "\u00b4", shift: "`",      alt_shift: "|",      alt: null, special: null       },
    {default: null,     shift: null,     alt_shift: null,     alt: null, special: "backspace"}
  ],
  [
    {default: null,     shift: null,     alt_shift: null,     alt: null, special: "spacer"},
    {default: "q",      shift: "Q",      alt_shift: null,     alt: null, special: null    },
    {default: "w",      shift: "W",      alt_shift: null,     alt: null, special: null    },
    {default: "e",      shift: "E",      alt_shift: "\u20ac", alt: null, special: null    },
    {default: "r",      shift: "R",      alt_shift: null,     alt: null, special: null    },
    {default: "t",      shift: "T",      alt_shift: null,     alt: null, special: null    },
    {default: "y",      shift: "Y",      alt_shift: null,     alt: null, special: null    },
    {default: "u",      shift: "U",      alt_shift: null,     alt: null, special: null    },
    {default: "i",      shift: "I",      alt_shift: null,     alt: null, special: null    },
    {default: "o",      shift: "O",      alt_shift: null,     alt: null, special: null    },
    {default: "p",      shift: "P",      alt_shift: null,     alt: null, special: null    },
    {default: "\u00e5", shift: "\u00c5", alt_shift: null,     alt: null, special: null    },
    {default: "\u00a8", shift: "^",      alt_shift: "~" ,     alt: null, special: null    },
    {default: "'",      shift: "*",      alt_shift: null,     alt: null, special: null    },
    {default: null,     shift: null,     alt_shift: null,     alt: null, special: "spacer"}
  ],
  [
    {default: null,     shift: null,     alt_shift: null, alt: null, special: "spacer"},
    {default: null,     shift: null,     alt_shift: null, alt: null, special: "spacer"},
    {default: null,     shift: null,     alt_shift: null, alt: null, special: "spacer"},
    {default: null,     shift: null,     alt_shift: null, alt: null, special: "spacer"},
    {default: null,     shift: null,     alt_shift: null, alt: null, special: "spacer"},
    {default: null,     shift: null,     alt_shift: null, alt: null, special: "spacer"},
    {default: null,     shift: null,     alt_shift: null, alt: null, special: "spacer"},
    {default: "a",      shift: "A",      alt_shift: null, alt: null, special: null    },
    {default: "s",      shift: "S",      alt_shift: null, alt: null, special: null    },
    {default: "d",      shift: "D",      alt_shift: null, alt: null, special: null    },
    {default: "f",      shift: "F",      alt_shift: null, alt: null, special: null    },
    {default: "g",      shift: "G",      alt_shift: null, alt: null, special: null    },
    {default: "h",      shift: "H",      alt_shift: null, alt: null, special: null    },
    {default: "j",      shift: "J",      alt_shift: null, alt: null, special: null    },
    {default: "k",      shift: "K",      alt_shift: null, alt: null, special: null    },
    {default: "l",      shift: "L",      alt_shift: null, alt: null, special: null    },
    {default: "\u00e6", shift: "\u00c6", alt_shift: null, alt: null, special: null    },
    {default: "\u00f8", shift: "\u00d8", alt_shift: null, alt: null, special: null    },
    {default: null,     shift: null,     alt_shift: null, alt: null, special: "enter" }
  ],
  [
    {default: null, shift: null, alt_shift: null,     alt: null, special: "shift"},
    {default: "<",  shift: ">",  shift_alt: "\\",     alt: null, special: null   },
    {default: "z",  shift: "Z",  shift_alt: null,     alt: null, special: null   },
    {default: "x",  shift: "X",  shift_alt: null,     alt: null, special: null   },
    {default: "c",  shift: "C",  shift_alt: null,     alt: null, special: null   },
    {default: "v",  shift: "V",  shift_alt: null,     alt: null, special: null   },
    {default: "b",  shift: "B",  shift_alt: null,     alt: null, special: null   },
    {default: "n",  shift: "N",  shift_alt: null,     alt: null, special: null   },
    {default: "m",  shift: "M",  shift_alt: "\u03bc", alt: null, special: null   },
    {default: ",",  shift: ";",  shift_alt: null,     alt: null, special: null   },
    {default: ".",  shift: ":",  shift_alt: null,     alt: null, special: null   },
    {default: "-",  shift: "_",  shift_alt: null,     alt: null, special: null   },
    {default: null, shift: null, alt_shift: null,     alt: null, special: "shift"}
  ],
  [
    {default: null, shift: null, alt_shift: null, alt: null, special: "spacer"},
    {default: null, shift: null, alt_shift: null, alt: null, special: "space" },
    {default: null, shift: null, alt_shift: null, alt: null, special: "spacer"}
  ]
]);
