multiLangKeyboard.addKeyboard('Lithuanian', 'lt', [
  [
    {default: "`",      shift: "~",      alt_shift: null, alt: null, special: null       },
    {default: "\u0105", shift: "\u0104", alt_shift: null, alt: null, special: null       },
    {default: "\u010D", shift: "\u010C", alt_shift: null, alt: null, special: null       },
    {default: "\u0119", shift: "\u0118", alt_shift: null, alt: null, special: null       },
    {default: "\u0117", shift: "\u0116", alt_shift: null, alt: null, special: null       },
    {default: "\u012F", shift: "\u012E", alt_shift: null, alt: null, special: null       },
    {default: "\u0161", shift: "\u0160", alt_shift: null, alt: null, special: null       },
    {default: "\u0173", shift: "\u0172", alt_shift: null, alt: null, special: null       },
    {default: "\u016B", shift: "\u016A", alt_shift: null, alt: null, special: null       },
    {default: "\u201E", shift: "(",      alt_shift: null, alt: null, special: null       },
    {default: "\u201C", shift: ")",      alt_shift: null, alt: null, special: null       },
    {default: "-",      shift: "_",      alt_shift: null, alt: null, special: null       },
    {default: "\u017E", shift: "\u017D", alt_shift: null, alt: null, special: null       },
    {default: null,     shift: null,     alt_shift: null, alt: null, special: "backspace"}
  ],
  [
    {default: null, shift: null, alt_shift: null, alt: null, special: "spacer"},
    {default: "q",  shift: "Q",  alt_shift: null, alt: null, special: null    },
    {default: "w",  shift: "W",  alt_shift: null, alt: null, special: null    },
    {default: "e",  shift: "E",  alt_shift: null, alt: null, special: null    },
    {default: "r",  shift: "R",  alt_shift: null, alt: null, special: null    },
    {default: "t",  shift: "T",  alt_shift: null, alt: null, special: null    },
    {default: "y",  shift: "Y",  alt_shift: null, alt: null, special: null    },
    {default: "u",  shift: "U",  alt_shift: null, alt: null, special: null    },
    {default: "i",  shift: "I",  alt_shift: null, alt: null, special: null    },
    {default: "o",  shift: "O",  alt_shift: null, alt: null, special: null    },
    {default: "p",  shift: "P",  alt_shift: null, alt: null, special: null    },
    {default: "[",  shift: "{",  alt_shift: null, alt: null, special: null    },
    {default: "]",  shift: "}",  alt_shift: null, alt: null, special: null    },
    {default: "\\", shift: "|",  alt_shift: null, alt: null, special: null    },
    {default: null, shift: null, alt_shift: null, alt: null, special: "spacer"}
  ],
  [
    {default: null, shift: null, alt_shift: null, alt: null, special: "spacer"},
    {default: "a",  shift: "A",  alt_shift: null, alt: null, special: null    },
    {default: "s",  shift: "S",  alt_shift: null, alt: null, special: null    },
    {default: "d",  shift: "D",  alt_shift: null, alt: null, special: null    },
    {default: "f",  shift: "F",  alt_shift: null, alt: null, special: null    },
    {default: "g",  shift: "G",  alt_shift: null, alt: null, special: null    },
    {default: "h",  shift: "H",  alt_shift: null, alt: null, special: null    },
    {default: "j",  shift: "J",  alt_shift: null, alt: null, special: null    },
    {default: "k",  shift: "K",  alt_shift: null, alt: null, special: null    },
    {default: "l",  shift: "L",  alt_shift: null, alt: null, special: null    },
    {default: ";",  shift: ":",  alt_shift: null, alt: null, special: null    },
    {default: "'",  shift: '"',  alt_shift: null, alt: null, special: null    },
    {default: null, shift: null, alt_shift: null, alt: null, special: "enter" }
  ],
  [
    {default: null,     shift: null,     alt_shift: null, alt: null, special: "shift"},
    {default: "\u2013", shift: "\u20AC", alt_shift: null, alt: null, special: null   },
    {default: "z",      shift: "Z",      alt_shift: null, alt: null, special: null   },
    {default: "x",      shift: "X",      alt_shift: null, alt: null, special: null   },
    {default: "c",      shift: "C",      alt_shift: null, alt: null, special: null   },
    {default: "v",      shift: "V",      alt_shift: null, alt: null, special: null   },
    {default: "b",      shift: "B",      alt_shift: null, alt: null, special: null   },
    {default: "n",      shift: "N",      alt_shift: null, alt: null, special: null   },
    {default: "m",      shift: "M",      alt_shift: null, alt: null, special: null   },
    {default: ",",      shift: "<",      alt_shift: null, alt: null, special: null   },
    {default: ".",      shift: ">",      alt_shift: null, alt: null, special: null   },
    {default: "/",      shift: "?",      alt_shift: null, alt: null, special: null   },
    {default: null,     shift: null,     alt_shift: null, alt: null, special: "shift"}
  ],
  [
    {default: null, shift: null, alt_shift: null, alt: null, special: "spacer"},
    {default: null, shift: null, alt_shift: null, alt: null, special: "space" },
    {default: null, shift: null, alt_shift: null, alt: null, special: "spacer"}
  ]
]);
