multiLangKeyboard.addKeyboard('Slovak', 'sk', [
  [
    {default: ";",      shift: "\u00b0", alt_shift: null,     alt: null, special: null       },
    {default: "+",      shift: "1",      alt_shift: "~",      alt: null, special: null       },
    {default: "\u013E", shift: "2",      alt_shift: "\u02C7", alt: null, special: null       },
    {default: "\u0161", shift: "3",      alt_shift: "^",      alt: null, special: null       },
    {default: "\u010D", shift: "4",      alt_shift: "\u02D8", alt: null, special: null       },
    {default: "\u0165", shift: "5",      alt_shift: "\u00B0", alt: null, special: null       },
    {default: "\u017E", shift: "6",      alt_shift: "\u02DB", alt: null, special: null       },
    {default: "\u00FD", shift: "7",      alt_shift: "`",      alt: null, special: null       },
    {default: "\u00E1", shift: "8",      alt_shift: "\u02D9", alt: null, special: null       },
    {default: "\u00ED", shift: "9",      alt_shift: "\u00B4", alt: null, special: null       },
    {default: "\u00E9", shift: "0",      alt_shift: "\u02DD", alt: null, special: null       },
    {default: "=",      shift: "%",      alt_shift: "\u00A8", alt: null, special: null       },
    {default: "\u00B4", shift: "\u02c7", alt_shift: "\u00B8", alt: null, special: null       },
    {default: null,     shift: null,     alt_shift: null,     alt: null, special: "backspace"}
  ],
  [
    {default: null,     shift: null, alt_shift: null,     alt: null, special: "spacer"},
    {default: "q",      shift: "Q",  alt_shift: "\\",     alt: null, special: null    },
    {default: "w",      shift: "W",  alt_shift: "|",      alt: null, special: null    },
    {default: "e",      shift: "E",  alt_shift: "\u20AC", alt: null, special: null    },
    {default: "r",      shift: "R",  alt_shift: null,     alt: null, special: null    },
    {default: "t",      shift: "T",  alt_shift: null,     alt: null, special: null    },
    {default: "z",      shift: "Z",  alt_shift: null,     alt: null, special: null    },
    {default: "u",      shift: "U",  alt_shift: null,     alt: null, special: null    },
    {default: "i",      shift: "I",  alt_shift: null,     alt: null, special: null    },
    {default: "o",      shift: "O",  alt_shift: null,     alt: null, special: null    },
    {default: "p",      shift: "P",  alt_shift: "'",      alt: null, special: null    },
    {default: "\u00FA", shift: "/",  alt_shift: "\u00F7", alt: null, special: null    },
    {default: "\u00E4", shift: "(",  alt_shift: "\u00D7", alt: null, special: null    },
    {default: "\u0148", shift: ")",  alt_shift: "\u00A4", alt: null, special: null    },
    {default: null,     shift: null, alt_shift: null,     alt: null, special: "spacer"}
  ],
  [
    {default: null,     shift: null, alt_shift: null,     alt: null, special: "spacer"},
    {default: "a",      shift: "A",  alt_shift: null,     alt: null, special: null    },
    {default: "s",      shift: "S",  alt_shift: "\u0111", alt: null, special: null    },
    {default: "d",      shift: "D",  alt_shift: "\u0110", alt: null, special: null    },
    {default: "f",      shift: "F",  alt_shift: "[",      alt: null, special: null    },
    {default: "g",      shift: "G",  alt_shift: "]",      alt: null, special: null    },
    {default: "h",      shift: "H",  alt_shift:  null,    alt: null, special: null    },
    {default: "j",      shift: "J",  alt_shift:  null,    alt: null, special: null    },
    {default: "k",      shift: "K",  alt_shift: "\u0142", alt: null, special: null    },
    {default: "l",      shift: "L",  alt_shift: "\u0141", alt: null, special: null    },
    {default: "\u00F4", shift: '"',  alt_shift: "$",      alt: null, special: null    },
    {default: "\u00A7", shift: "!",  alt_shift: "\u00DF", alt: null, special: null    },
    {default: null,     shift: null, alt_shift: null,     alt: null, special: "spacer"}
  ],
  [
    {default: null, shift: null, alt_shift: null, alt: null, special: "shift"},
    {default: "&",  shift: "*",  alt_shift: "<",  alt: null, special: null   },
    {default: "y",  shift: "Y",  alt_shift: ">",  alt: null, special: null   },
    {default: "x",  shift: "X",  alt_shift: "#",  alt: null, special: null   },
    {default: "c",  shift: "C",  alt_shift: "&",  alt: null, special: null   },
    {default: "v",  shift: "V",  alt_shift: "@",  alt: null, special: null   },
    {default: "b",  shift: "B",  alt_shift: "{",  alt: null, special: null   },
    {default: "n",  shift: "N",  alt_shift: "}",  alt: null, special: null   },
    {default: "m",  shift: "M",  alt_shift: null, alt: null, special: null   },
    {default: ",",  shift: "?",  alt_shift: "<",  alt: null, special: null   },
    {default: ".",  shift: ":",  alt_shift: ">",  alt: null, special: null   },
    {default: "-",  shift: "_",  alt_shift: "*",  alt: null, special: null   },
    {default: null, shift: null, alt_shift: null, alt: null, special: "shift"}
  ],
  [
    {default: null, shift: null, alt_shift: null, alt: null, special: "spacer"},
    {default: null, shift: null, alt_shift: null, alt: null, special: "alt"   },
    {default: null, shift: null, alt_shift: null, alt: null, special: "space" },
    {default: null, shift: null, alt_shift: null, alt: null, special: "alt"   },
    {default: null, shift: null, alt_shift: null, alt: null, special: "spacer"}
  ]
]);
