multiLangKeyboard.addKeyboard('Estonian', 'et', [
  [
    {default: "\u02C7", shift: "~",      alt_shift: null,     alt: null,     special: null       },
    {default: "1",      shift: "!",      alt_shift: null,     alt: null,     special: null       },
    {default: "2",      shift: '"',      alt_shift: "@",      alt: "@",      special: null       },
    {default: "3",      shift: "#",      alt_shift: "\u00A3", alt: "\u00A3", special: null       },
    {default: "4",      shift: "\u00A4", alt_shift: "$",      alt: "$",      special: null       },
    {default: "5",      shift: "%",      alt_shift: "\u20AC", alt: null,     special: null       },
    {default: "6",      shift: "&",      alt_shift:  null,    alt: null,     special: null       },
    {default: "7",      shift: "/",      alt_shift:  "{",     alt: "{",      special: null       },
    {default: "8",      shift: "(",      alt_shift:  "[",     alt: "[",      special: null       },
    {default: "9",      shift: ")",      alt_shift:  "]",     alt: "]",      special: null       },
    {default: "0",      shift: "=",      alt_shift:  "}",     alt: "}",      special: null       },
    {default: "+",      shift: "?",      alt_shift:  "\\",    alt: "\\",     special: null       },
    {default: "\u00B4", shift: "`",      alt_shift:  null,    alt: null,     special: null       },
    {default: null,     shift: null,     alt_shift: null,     alt: null,     special: "backspace"}
  ],
  [
    {default: null,     shift: null,      alt_shift: null,      alt: null,     special: "spacer"},
    {default: "q",      shift: "Q",       alt_shift: null,      alt: null,     special: null    },
    {default: "w",      shift: "W",       alt_shift: null,      alt: null,     special: null    },
    {default: "e",      shift: "E",       alt_shift: "\u20AC",  alt: null,     special: null    },
    {default: "r",      shift: "R",       alt_shift: null,      alt: null,     special: null    },
    {default: "t",      shift: "T",       alt_shift: null,      alt: null,     special: null    },
    {default: "y",      shift: "Y",       alt_shift: null,      alt: null,     special: null    },
    {default: "u",      shift: "U",       alt_shift: null,      alt: null,     special: null    },
    {default: "i",      shift: "I",       alt_shift: null,      alt: null,     special: null    },
    {default: "o",      shift: "O",       alt_shift: null,      alt: null,     special: null    },
    {default: "p",      shift: "P",       alt_shift: null,      alt: null,     special: null    },
    {default: "\u00FC", shift: "\u00DC",  alt_shift: null,      alt: null,     special: null    },
    {default: "\u00F5", shift: "\u00D5",  alt_shift: "\u00A7",  alt: "\u00A7", special: null    },
    {default: "'",      shift: "*",       alt_shift: "\u00BD",  alt: "\u00BD", special: null    },
    {default: null,     shift: null,      alt_shift: null,      alt: null,     special: "spacer"}
  ],
  [
    {default: null,     shift: null,      alt_shift: null,      alt: null,     special: "spacer"},
    {default: null,     shift: null,      alt_shift: null,      alt: null,     special: "spacer"},
    {default: null,     shift: null,      alt_shift: null,      alt: null,     special: "spacer"},
    {default: null,     shift: null,      alt_shift: null,      alt: null,     special: "spacer"},
    {default: null,     shift: null,      alt_shift: null,      alt: null,     special: "spacer"},
    {default: null,     shift: null,      alt_shift: null,      alt: null,     special: "spacer"},
    {default: null,     shift: null,      alt_shift: null,      alt: null,     special: "spacer"},
    {default: "a",      shift: "A",       alt_shift: null,      alt: null,     special: null    },
    {default: "s",      shift: "S",       alt_shift: "\u0160",  alt: "\u0161", special: null    },
    {default: "d",      shift: "D",       alt_shift: null,      alt: null,     special: null    },
    {default: "f",      shift: "F",       alt_shift: null,      alt: null,     special: null    },
    {default: "g",      shift: "G",       alt_shift: null,      alt: null,     special: null    },
    {default: "h",      shift: "H",       alt_shift: null,      alt: null,     special: null    },
    {default: "j",      shift: "J",       alt_shift: null,      alt: null,     special: null    },
    {default: "k",      shift: "K",       alt_shift: null,      alt: null,     special: null    },
    {default: "l",      shift: "L",       alt_shift: null,      alt: null,     special: null    },
    {default: "\u00F6", shift: "\u00D6",  alt_shift: null,      alt: null,     special: null    },
    {default: "\u00E4", shift: "\u00C4",  alt_shift: "^",       alt: "^",      special: null    },
    {default: null,     shift: null,      alt_shift: null,      alt: null,     special: "enter" }
  ],
  [
    {default: null, shift: null, alt_shift: null,     alt: null,     special: "shift"},
    {default: "<",  shift: ">",  alt_shift: "|",      alt: "|",      special: null   },
    {default: "z",  shift: "Z",  alt_shift: "\u017D", alt: "\u017E", special: null   },
    {default: "x",  shift: "X",  alt_shift: null,     alt: null,     special: null   },
    {default: "c",  shift: "C",  alt_shift: null,     alt: null,     special: null   },
    {default: "v",  shift: "V",  alt_shift: null,     alt: null,     special: null   },
    {default: "b",  shift: "B",  alt_shift: null,     alt: null,     special: null   },
    {default: "n",  shift: "N",  alt_shift: null,     alt: null,     special: null   },
    {default: "m",  shift: "M",  alt_shift: null,     alt: null,     special: null   },
    {default: ",",  shift: ";",  alt_shift: null,     alt: null,     special: null   },
    {default: ".",  shift: ":",  alt_shift: null,     alt: null,     special: null   },
    {default: "-",  shift: "_",  alt_shift: null,     alt: null,     special: null   },
    {default: null, shift: null, alt_shift: null,     alt: null,     special: "shift"}
  ],
  [
    {default: null, shift: null, alt_shift: null, alt: null, special: "spacer"},
    {default: null, shift: null, alt_shift: null, alt: null, special: "alt"   },
    {default: null, shift: null, alt_shift: null, alt: null, special: "space" },
    {default: null, shift: null, alt_shift: null, alt: null, special: "alt"   },
    {default: null, shift: null, alt_shift: null, alt: null, special: "spacer"}
  ]
]);
